### ISSUE TITLE
GirderItemId, GirderItemIds

### ISSUE THREAD

**Issue by Xaxetrov** [girder/girder_worker_utils#39]
Is there a plan to create a function similar to GirderFileId but for items ? A bit like in the docker plugin where an item is downloaded to the worker.

I have a use case where I need to download several items to a worker. Would you be interested if I propose in a PR:
- A function to download 1 item to a folder.
- A function to download several items to several folders or a folder with nested subfolders
?

**Comment by kotfic** [comment]
We're always happy to welcome contributions! As a little background, the primary goal of this repo is to establish the transform interface. The examples that are included (e.g. `GirderFileId`) exist to exercise that interface and provide some guidance. 

We're trying to strike a balance between generality and simplicity so while a function to download an item to a folder may be a good candidate,  a function that downloads several items to several folders may need to either (1) make some opinionated implementation choices that effect generality,  or (2) provide a wide array of options for various use cases that effect simplicity.   In these cases we'd expect the transform to be implemented in some downstream package that was closer to the problem the transform solves.  This isn't to dissuade you from opening a PR with a multi-item implementation just to let you know what some of the background concerns are.

Cheers!

**Comment by Xaxetrov** [comment]
Quick question before closing the issue:
We are going to implement a transform that downloads several files to a worker's temporary folder (GirderFileIds). Seeing your previous comment, am I right thinking you would not want to see it in this repo ?

**Comment by kotfic** [comment]
No i'm open to the idea, it depends on the implementation. I just want
to avoid adding complexity to meet multiple use-cases. If there is a
generally useful implementation I think that would be fine.
